#!/usr/bin/env node
/**
 * Regenerate tests/fixtures/wire-shape-baseline.json from a local
 * checkout of getaxonflow/axonflow's docs/api directory.
 *
 * Usage:
 *   node scripts/wire-shape/refresh.js <specs_dir> [--sha <SHA>]
 *
 * When --sha is omitted, the script tries `git -C <specs_dir>
 * rev-parse HEAD` to pin the commit. If neither is available, it
 * exits non-zero rather than write a baseline with an empty
 * openapi_specs_sha (the next CI run would fail at bootstrap).
 *
 * The baseline is written atomically (temp-file + rename) so a
 * mid-encode crash can't leave a truncated file behind.
 */

'use strict';

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const {
  loadAllSchemas,
  discoverSDKInterfaces,
  writeBaseline,
  difference,
  BASELINE_PATH,
} = require('./lib');

function gitHeadSHA(dir) {
  try {
    return execSync(`git -C "${dir}" rev-parse HEAD`, {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return '';
  }
}

function main() {
  const args = process.argv.slice(2);
  let specsDir = null;
  let explicitSha = null;
  for (let i = 0; i < args.length; i += 1) {
    if (args[i] === '--sha') {
      if (i + 1 >= args.length) {
        // `--sha` as the last token used to be silently consumed as
        // a positional `specsDir`, masking the missing value. Fail
        // loudly instead.
        console.error('error: --sha requires a value (e.g. --sha bf1ca22…)');
        process.exit(2);
      }
      explicitSha = args[i + 1];
      i += 1;
    } else if (!specsDir) {
      specsDir = args[i];
    }
  }

  if (!specsDir) {
    console.error('usage: node scripts/wire-shape/refresh.js <specs_dir> [--sha <SHA>]');
    process.exit(2);
  }
  if (!fs.existsSync(specsDir) || !fs.statSync(specsDir).isDirectory()) {
    console.error(`error: ${specsDir} is not a directory`);
    process.exit(2);
  }

  const sha = (explicitSha !== null ? explicitSha : gitHeadSHA(specsDir)).trim();
  if (!sha) {
    console.error(
      'error: could not determine OpenAPI specs commit SHA.\n' +
        '  Either run this script against a specs_dir that sits inside a git\n' +
        '  checkout of the getaxonflow/axonflow community mirror, or pass\n' +
        '  --sha <commit-sha> explicitly. An empty SHA would poison\n' +
        '  tests/fixtures/wire-shape-baseline.json and break the next CI\n' +
        '  wire-shape-contract run at bootstrap.'
    );
    process.exit(2);
  }

  const { merged, crossSpecDuplicates, intraFileDuplicates } = loadAllSchemas(specsDir);
  const sdk = discoverSDKInterfaces();

  const registered = [];
  const perTypeDrift = {};
  for (const [name, sdkFields] of Object.entries(sdk)) {
    const specFields = merged[name];
    if (!specFields) {
      continue;
    }
    registered.push(name);
    const sdkOnly = difference(sdkFields, specFields);
    const specOnly = difference(specFields, sdkFields);
    if (sdkOnly.length === 0 && specOnly.length === 0) {
      continue;
    }
    perTypeDrift[name] = { sdk_only: sdkOnly, spec_only: specOnly };
  }
  registered.sort();

  const baseline = {
    _comment:
      'Baseline of KNOWN wire-shape drift between the TS SDK and the OpenAPI ' +
      'specs. Generated by scripts/wire-shape/refresh.js. The CI gate fails on ' +
      'drift OUTSIDE this baseline. Entries here should be burned down over ' +
      'time via targeted fix PRs. See axonflow-enterprise tracking issue (QF-12 follow-up).',
    openapi_specs_sha: sha,
    cross_spec_duplicates: sortObject(crossSpecDuplicates),
    intra_file_duplicates: sortObject(intraFileDuplicates),
    registered_types: registered,
    per_type_drift: sortObject(perTypeDrift),
  };

  writeBaseline(baseline);
  console.log(`Wrote baseline: ${path.relative(process.cwd(), BASELINE_PATH)}`);
  console.log(`  openapi_specs_sha:       ${sha}`);
  console.log(`  cross_spec_duplicates:   ${Object.keys(crossSpecDuplicates).length}`);
  console.log(`  intra_file_duplicates:   ${Object.keys(intraFileDuplicates).length} file(s)`);
  console.log(`  registered_types:        ${registered.length}`);
  console.log(`  per_type_drift:          ${Object.keys(perTypeDrift).length}`);
}

function sortObject(obj) {
  const sorted = {};
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = obj[key];
  }
  return sorted;
}

main();
