#!/usr/bin/env python3
"""Derive tests/fixtures/openapi/ from the platform's docs/api specs.

Usage:
    python scripts/snapshot_openapi_schemas.py <specs_dir> <out_dir> --source-commit <SHA>
    python scripts/snapshot_openapi_schemas.py --self-test
    python scripts/snapshot_openapi_schemas.py --check-snapshot tests/fixtures/openapi

The wire-shape contract reads, from each spec, the schema declarations under
``components.schemas`` and the names of each declaration's ``properties``.
This script writes exactly that, one output file per input ``*.yaml`` under
the same file name:

    components:
      schemas:
        "SchemaName":
          properties:
            "field": {}
        "RefOnlySchema": {}

It works on the YAML node graph, not on a parsed dictionary, so it keeps what a
dictionary would lose: every declaration in source order, a schema declared
twice in one file, and a declaration without properties. A loader that counts
in-file duplicates, or one where the last declaration wins, reads the same
thing from the snapshot as from the source.

It drops descriptions, types, examples, paths and the ``info`` block. The
platform specs carry the platform's own licence statement there, and this
repository is MIT.

It refuses a YAML merge key (``<<``) under ``schemas`` or ``properties``:
loaders disagree on whether to expand one, so no single derivation could be
right for all of them.

Output is deterministic, so a change in the snapshot is a change in the
platform's schemas. ``--self-test`` checks all of the above on a planted spec
and needs nothing beyond Python and PyYAML, so any SDK repository can run it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path

import yaml

HEADER_FIRST_LINE = "# GENERATED by scripts/snapshot_openapi_schemas.py - do not edit."

# How many times PLANTED declares its duplicated schema.
PLANTED_DUPLICATE_DECLARATIONS = 2

Declaration = tuple[str, "list[str] | None"]


def _child(node: yaml.Node | None, key: str) -> yaml.Node | None:
    if not isinstance(node, yaml.MappingNode):
        return None
    for k, v in node.value:
        if isinstance(k, yaml.ScalarNode) and k.value == key:
            return v
    return None


def _refuse_merge_keys(node: yaml.MappingNode, where: str) -> None:
    for k, _ in node.value:
        if isinstance(k, yaml.ScalarNode) and k.tag == "tag:yaml.org,2002:merge":
            msg = f"a YAML merge key under {where} cannot be derived faithfully"
            raise ValueError(msg)


def declarations(text: str) -> list[Declaration]:
    """Every schema declaration in source order: (name, property names or None).

    ``None`` means the declaration has no non-empty ``properties`` mapping.
    Duplicate names and duplicate property keys are kept, in order.
    """
    root = yaml.compose(text)
    schemas = _child(_child(root, "components"), "schemas")
    if not isinstance(schemas, yaml.MappingNode):
        return []
    _refuse_merge_keys(schemas, "components.schemas")
    out: list[Declaration] = []
    for key, value in schemas.value:
        if not isinstance(key, yaml.ScalarNode):
            continue
        props = _child(value, "properties")
        if isinstance(props, yaml.MappingNode) and props.value:
            _refuse_merge_keys(props, f"components.schemas.{key.value}.properties")
            names = [k.value for k, _ in props.value if isinstance(k, yaml.ScalarNode)]
            out.append((key.value, names or None))
        else:
            out.append((key.value, None))
    return out


def render(source_name: str, source_bytes: bytes, commit: str) -> str:
    """Render the derived document for one spec, with the header naming its source."""
    digest = hashlib.sha256(source_bytes).hexdigest()
    lines = [
        HEADER_FIRST_LINE,
        f"# Source: docs/api/{source_name} at platform commit {commit}",
        f"# Source sha256: {digest}",
        "# Schema declarations and property names only; see tests/fixtures/openapi/README.md.",
        "components:",
    ]
    decls = declarations(source_bytes.decode("utf-8"))
    if not decls:
        lines.append("  schemas: {}")
    else:
        lines.append("  schemas:")
        for name, props in decls:
            if props is None:
                lines.append(f"    {json.dumps(name)}: {{}}")
                continue
            lines.append(f"    {json.dumps(name)}:")
            lines.append("      properties:")
            lines.extend(f"        {json.dumps(field)}: {{}}" for field in props)
    return "\n".join(lines) + "\n"


def _body(text: str) -> list[str]:
    return [line for line in text.splitlines() if line and not line.startswith("#")]


def check_snapshot(snapshot_dir: Path) -> list[str]:
    """Problems with a committed snapshot, or an empty list.

    Every file must carry the generated header, and its body must be exactly
    what this script derives from it again. That refuses anything beyond the
    derived form: prose, types, a spec copied in verbatim, a re-formatted file.
    It cannot see a declaration added by hand in the derived form itself; only
    the source could. What makes every change to the snapshot visible is the
    wire-shape job's pin guard, which requires the spec-pin-bump label for
    any change under the snapshot directory.
    """
    files = sorted(snapshot_dir.glob("*.yaml"))
    if not files:
        return [f"{snapshot_dir} holds no *.yaml"]
    problems: list[str] = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()
        if not lines or lines[0] != HEADER_FIRST_LINE:
            problems.append(f"{path.name}: missing the generated header")
            continue
        again = render(path.name, text.encode("utf-8"), "check")
        if _body(text) != _body(again):
            problems.append(f"{path.name}: not in the derived form")
    return problems


def derive_dir(specs_dir: Path, out_dir: Path, commit: str) -> list[Path]:
    sources = sorted(specs_dir.glob("*.yaml"))
    if not sources:
        msg = f"no *.yaml files in {specs_dir}"
        raise FileNotFoundError(msg)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for src in sources:
        out = out_dir / src.name
        out.write_text(render(src.name, src.read_bytes(), commit), encoding="utf-8")
        written.append(out)
    return written


PLANTED = """\
openapi: 3.0.3
info:
  title: Planted
  license:
    name: PLANTED-LICENCE-NAME
  description: PLANTED-INFO-PROSE
paths:
  /x:
    get:
      description: PLANTED-PATH-PROSE
components:
  schemas:
    WithProps:
      description: PLANTED-SCHEMA-PROSE
      properties:
        b_field:
          type: string
          description: PLANTED-FIELD-PROSE
        a_field:
          type: integer
    Duplicated:
      properties:
        first: {type: string}
    RefOnly:
      $ref: '#/components/schemas/WithProps'
    EmptyProps:
      properties: {}
    Scalar: just-a-string
    Duplicated:
      properties:
        second: {type: string}
    "Needs: quoting":
      properties:
        "odd key": {type: string}
"""


def self_test() -> int:
    """Check the derivation's properties on a planted spec. Returns an exit code."""
    failures: list[str] = []

    def check(ok: bool, what: str) -> None:
        print(f"{'PASS' if ok else 'FAIL'}: {what}")
        if not ok:
            failures.append(what)

    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "src"
        src.mkdir()
        (src / "planted-api.yaml").write_text(PLANTED, encoding="utf-8")
        first = derive_dir(src, Path(tmp) / "a", "c0ffee")[0].read_text(encoding="utf-8")
        second = derive_dir(src, Path(tmp) / "b", "c0ffee")[0].read_text(encoding="utf-8")
        body = "\n".join(line for line in first.splitlines() if not line.startswith("#"))
        check(
            declarations(body) == declarations(PLANTED),
            "every declaration, duplicates and property-less ones included, survives in order",
        )
        check(
            [n for n, _ in declarations(body)].count("Duplicated")
            == PLANTED_DUPLICATE_DECLARATIONS,
            "a schema declared twice in one file is still declared twice",
        )
        check(
            yaml.safe_load(body)["components"]["schemas"]["Duplicated"]
            == {"properties": {"second": {}}},
            "a last-declaration-wins loader reads the same winner as from the source",
        )
        check(
            not any(
                p in first
                for p in (
                    "PLANTED-LICENCE",
                    "PLANTED-INFO",
                    "PLANTED-PATH",
                    "PLANTED-SCHEMA",
                    "PLANTED-FIELD",
                )
            ),
            "no prose survives the derivation",
        )
        check(first == second, "the derivation is deterministic")
        check(first.splitlines()[0] == HEADER_FIRST_LINE, "the output carries the generated header")
        try:
            declarations("components:\n  schemas:\n    <<: {A: {}}\n")
            check(False, "a merge key under schemas is refused")
        except ValueError:
            check(True, "a merge key under schemas is refused")
        derived = Path(tmp) / "a"
        check(check_snapshot(derived) == [], "a freshly derived snapshot checks clean")
        edited = derived / "planted-api.yaml"
        edited.write_text(
            first + '    "Extra":\n      description: PLANTED-PROSE\n', encoding="utf-8"
        )
        check(check_snapshot(derived) != [], "a snapshot carrying prose is refused")
    print(f"\nself-test: {'FAIL' if failures else 'PASS'} ({len(failures)} failure(s))")
    return 1 if failures else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "specs_dir", type=Path, nargs="?", help="directory holding the platform's docs/api *.yaml"
    )
    parser.add_argument(
        "out_dir", type=Path, nargs="?", help="directory to write the derived files into"
    )
    parser.add_argument("--source-commit", help="platform commit the specs were taken from")
    parser.add_argument(
        "--self-test", action="store_true", help="check the derivation on a planted spec"
    )
    parser.add_argument(
        "--check-snapshot",
        type=Path,
        metavar="DIR",
        help="check that a committed snapshot is exactly this script's derived form",
    )
    args = parser.parse_args(argv)

    if args.self_test:
        return self_test()
    if args.check_snapshot is not None:
        problems = check_snapshot(args.check_snapshot)
        for problem in problems:
            print(f"FAIL: {problem}")
        print(f"check-snapshot: {'FAIL' if problems else 'PASS'} ({args.check_snapshot})")
        return 1 if problems else 0
    if args.specs_dir is None or args.out_dir is None or not args.source_commit:
        parser.error(
            "specs_dir, out_dir and --source-commit are required"
            " unless --self-test or --check-snapshot"
        )
    try:
        written = derive_dir(args.specs_dir, args.out_dir, args.source_commit)
    except (FileNotFoundError, ValueError) as e:
        print(str(e), file=sys.stderr)
        return 1
    for out in written:
        count = len(declarations(out.read_text(encoding="utf-8")))
        print(f"{out.name}: {count} schema declarations -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
